# Site settings
title: Aakash Saboo
email: aakashsaboo2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Industrial Engineer. Researching in Medical Imaging and Self-Supervised Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.aakash-saboo.github.io" # the base hostname & protocol for your site
production_url: "https://www.aakash-saboo.github.io"
github_username: aakash-saboo
permalink: /blog/:year/:month/:title.html

twitter:
  username: AakashSaboo

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
